update chapter_stack_and_queue/index.md
krahets/hello-algo pull request #1035
Opened 2024-01-09 01:29 UTC by YangXuanyi

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [ ] I've tested the code and ensured the outputs are the same as the outputs of reference code.
- [ ] I've checked the code (formatting, comments, indentation, file header, etc) carefully.
- [ ] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

2024-01-10 10:29 UTC, krahets commented
Randomly assign 2 reviewers ['@K3v123' '@yadie'] to  the pull request #1035

2024-01-10 23:25 UTC, K3v123 approved these changes

2024-01-10 23:29 UTC, K3v123 commented
looks good to me. Although I do prefer the original on the second sentence, but both are good anyways.

2024-01-11 08:39 UTC, krahets commented
> Although I do prefer the original on the second sentence, but both are good anyways.

Me too

2024-01-13 01:47 UTC, YangXuanyi commented
@krahets @K3v123 Thank you for your opinions. I personally think the second sentence I provided may be more detailed. Since you all agree that both methods are fine, I'm going to use my own modification of this one.

2024-01-27 14:11 UTC, yanedie requested changes

2024-01-27 14:11 UTC, yanedie commented on docs-en/chapter_stack_and_queue/index.md
> +    They represent the logical relationships of Last-In-First-Out (LIFO) and First-In-First-Out (FIFO), respectively.
不需要逗号。

2024-01-27 23:55 UTC, YangXuanyi commented on docs-en/chapter_stack_and_queue/index.md
> +    They represent the logical relationships of Last-In-First-Out (LIFO) and First-In-First-Out (FIFO), respectively.
非常感谢您的建议。这个逗号的问题我在翻译的时候也查阅了一些资料，我发现从语法的角度上来说加和不加都可以，但是看到一些科技论文里大部分都是加上的。您提到这个后我也不确定了，可以请详细阐述为什么要删除逗号吗？想交流学习下这个词的用法

2024-01-28 11:35 UTC, yanedie commented on docs-en/chapter_stack_and_queue/index.md
> +    They represent the logical relationships of Last-In-First-Out (LIFO) and First-In-First-Out (FIFO), respectively.
抱歉，我在各个字典里看到的例句都是不加逗号的，然后我查阅了各个杂志期刊发现也有加的。

2024-01-28 11:36 UTC, yanedie approved these changes

2024-01-28 11:36 UTC, yanedie commented on docs-en/chapter_stack_and_queue/index.md
> +    They represent the logical relationships of Last-In-First-Out (LIFO) and First-In-First-Out (FIFO), respectively.
> 非常感谢您的建议。这个逗号的问题我在翻译的时候也查阅了一些资料，我发现从语法的角度上来说加和不加都可以，但是看到一些科技论文里大部分都是加上的。您提到这个后我也不确定了，可以请详细阐述为什么要删除逗号吗？想交流学习下这个词的用法

抱歉，我在各个字典里看到的例句都是不加逗号的，然后我查阅了各个杂志期刊发现也有加的。

2024-01-28 11:38 UTC, krahets approved these changes

2024-01-28 11:38 UTC, merged