Add intial translation of the figures for the chapters of dynamic programming, greedy
krahets/hello-algo pull request #1336
Opened 2024-05-04 11:12 UTC by krahets

If this pull request (PR) pertains to **Chinese-to-English translation**, please confirm that you have read the contribution guidelines and complete the checklist below:

- [x] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [x] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.

2024-05-04 12:10 UTC, krahets commented
Please review the translation based on the following aspects:

1. Ensure the expression is authentic and accurate.
2. Maintain consistency between the Chinese and English versions. (Balancing with point 1)

In addition to content, please pay attention to the format:

1. It is expected to use `Roboto` font for normal text and `Roboto Mono` for formulas and code. These may be prone to mistakes since they are set manually.
2. The style and color of shapes and texts should be consistent between the two versions. (I made some color adjustments in the EN version to enhance readability, so please only report those that feel uncomfortable to you.)

2024-05-05 01:35 UTC, K3v123 reviewed
overall looks good to me.
the texts are accurately translated. its just some colors and stuff. some text is grey in CN but different in EN. also bolds. etc

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/climbing_stairs_constraint_example.png
the color of 3 was green on the CN ver. The en is not colored in green.

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dfs.png
The CN version equation "dp[i+1,j]" is not grey, so just wondering will the CN version text will be greyed for consistency.

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step1.png
the word "table" seems to be missing (same goes for others below). but it shouldn't be too much of a deal.

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step3.png
"dp table" same, missing

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_state_definition.png
the word "grid" on EN is not grey.

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_state_transition.png
"grid table" not written.

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_state_transfer.png
color of remove add and replace is gone in EN ver

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_example.png
color 3rd is not colored in green (en ver)

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/knapsack_problem.assets/knapsack_dp_comp_step1.png
dp is grey in cn while en is bold

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/knapsack_problem.assets/knapsack_dp_comp_step2.png
dp is grey in cn. same for below the "dp =" part

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_dynamic_programming/knapsack_problem.assets/knapsack_example.png
50 is bold in en ver. i personally like this better

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_example.png
Apple in EN while Banana in CN!!!!!

2024-05-05 01:35 UTC, K3v123 commented on en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_vs_dp.png
all header are bold while CN is grey.
and CN the color is orange and EN the "local optimum" is in red.
^this makes more sense. so will the CN version's text be red?

also the text color is bold i believe in CN while EN its not bold. or is it just because the text format changed?

2024-05-07 00:56 UTC, yuelinxin reviewed
Great work! No substantial problem, plz consider the mentioned points.

2024-05-10 03:47 UTC, frankliuao requested changes
Please see my comments. I didn't repeat my comment for all the pictures where I think 面值 should have been translated to "face value"

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/knapsack_problem.assets/knapsack_dp_step14.png
It's a little hard to read. 
Change it to "Return `20`, the maximum... backpack"

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step1.png
DP to `dp`?
面值 can be translated as "face value" – it's a real phrase in finance. 
Not sure about "denomination". Maybe 
"Variety of face values `n = 3`"

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step10.png
面值 can be translated as "face value" – it's a real phrase in finance.

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step12.png
面值 can be translated as "face value" – it's a real phrase in finance.

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step13.png
面值 can be translated as "face value" – it's a real phrase in finance.

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_strategy.png
I think it's fine to say "largest coin not exceeding the remaining amount"
The reason is that the largest coin which is <= the remaining amount should be the closest to it already. :)

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_vs_dp.png
There is a typo. "Local/global optimum", not "Local/global optmimum".

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_long_board.png
It was a direct Chinese to English translation. 
The more native way of saying this should be "The capacity will decrease if the longer board is moved inward"
No need for "definitely".

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_long_board.png
or use "surely"

2024-05-10 03:47 UTC, frankliuao commented on en/docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer1.png
or change it to "2(n-2) >= n is always true when n>=4".

2024-05-11 04:30 UTC, pengchzn commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step1.png
I think "denomination" is correct as it says in the dictionary [here](https://dictionary.cambridge.org/dictionary/english/denomination)

2024-05-15 15:58 UTC, RafaelCaso commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/climbing_stairs_constraint_example.png
This is the same concern I had. I think you two addressed it well. I also want to point out that in the constraint_example.png and constraint_state_transfer.png they say the same thing in two different ways 
- "Since two consecutive rounds cannot jump 1 stair..." 
- "Cannot jump 1 stair consecutively in two rounds..."

I think they should both use the same syntax (whichever the author prefers)

2024-05-15 16:45 UTC, RafaelCaso approved these changes
Frank did a good job of addressing the few concerns I had. Overall looks good. I understand these are captions, so the language needs to be short and direct. I focused on making sure they are consistent (which is the only feedback I gave)

2024-05-15 16:56 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/min_cost_cs_dp.png
"state-transition equation" has its dedicated meaning, background here:
https://en.wikipedia.org/wiki/State-transition_equation 
Again it's grammarly correct, but harder to read.

2024-05-15 16:59 UTC, frankliuao commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step1.png
I think you are right, @pengchzn I do see this word used describing the face values of bills. I think it's just less commonly used in your daily life. That maybe just me, though.

2024-05-15 17:17 UTC, RafaelCaso commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step1.png
I agree. Denomination is something we see written much more than we hear it spoken, but we do see it a lot. At an ATM, for example, they used to ask you 'what denomination do you prefer?' so if you wanted $100 and the denomination was 20, you would get 5 $20 bills. For a book like this, denomination is very reasonable in my opinion.

2024-05-31 05:06 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/climbing_stairs_constraint_example.png
All comments addressed, thx!

2024-05-31 05:06 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/climbing_stairs_constraint_example.png
thx

2024-05-31 05:07 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/climbing_stairs_constraint_example.png
thx

2024-05-31 05:10 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_problem_features.assets/min_cost_cs_dp.png
@pengchzn @frankliuao 

> Fom GPT-4: In the context of dynamic programming, the term "state transition equation" is more commonly used and recognized. This term describes the mathematical expression or formula that defines how the state of a dynamic system changes from one state to another based on certain inputs or actions. The equation typically encapsulates how the current state and the decisions made influence the next state.

The phrase "equation of state transition" might convey a similar meaning, but it is less standard and might not be immediately recognized or understood in the field of dynamic programming or related disciplines like control theory and systems engineering.

2024-05-31 05:15 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_example.png
Both terms are okay for me, although I personally prefer left-aligned English texts.

2024-05-31 05:22 UTC, krahets commented on en/docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_state_definition.png
> Minimize the sum of numbers on the path from the...

https://leetcode.com/problems/minimum-path-sum/

`Min path sum` is the heading of the problem, so I believe it is not ambiguous, and it's clear to show the relationship between the original problem and the sub-problems.

2024-05-31 05:42 UTC, krahets commented on en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.assets/coin_change_dp_step2.png
@RafaelCaso Which one do you prefer "as" or "with" here?

2024-05-31 06:29 UTC, krahets commented on en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_vs_dp.png
> ^this makes more sense. so will the CN version's text be red?

I agree. Red is more appropriate here

2024-05-31 07:58 UTC, krahets commented
Thanks for your thorough review! @frankliuao, @pengchzn, @yuelinxin, and @RafaelCaso, most of the comments have been addressed.
A few comments remain unresolved for further discussion. Please let me know if there's anything else that needs fixing.

2024-05-31 07:58 UTC, merged