Add array_queue.rs in chapter_stack_and_queue
krahets/hello-algo pull request #347
Opened 2023-02-07 01:42 UTC by WSL0809

If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

2023-02-08 16:57 UTC, krahets commented
Pending for reviewing by @sjinzh

2023-02-09 14:55 UTC, sjinzh requested changes

2023-02-09 14:55 UTC, sjinzh commented on codes/rust/array_queue.rs
> +/**
The location of this file should in "codes/rust/chapter_stack_and_queue/array_queue.rs"

2023-02-09 14:55 UTC, sjinzh commented on codes/rust/array_queue.rs
> +        "出队元素 poll = {:?} \n出队后 queue = {:?}",
"出队元素 poll = {:?} \n出队后 queue = {:?}"
should be 
"出队元素 poll = {:?}, 出队后 queue = {:?}"

2023-02-10 01:43 UTC, closed without merging