🦄 refactor(deque):  change LinkedList to VecDeque
krahets/hello-algo pull request #364
Opened 2023-02-13 12:42 UTC by xBLACKICEx

If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

I think replacing **LinkedList** with **VecDeque** is more in line with the general usage of the Rust language and more in line with the library of the title.

2023-02-13 15:32 UTC, krahets commented
To be reviewed by @sjinzh

2023-02-14 12:31 UTC, sjinzh requested changes

2023-02-14 12:31 UTC, sjinzh commented on codes/rust/chapter_stack_and_queue/deque.rs
> + * Author: sjinzh (sjinzh@gmail.com), (xBLACKICEx@outlook.com)
sjinzh (sjinzh@gmail.com), xBLACICEx (xBLACKICEx@outlook.com)

2023-02-14 12:31 UTC, sjinzh commented on codes/rust/chapter_stack_and_queue/queue.rs
> + * Author: sjinzh (sjinzh@gmail.com), (xBLACKICEx@outlook.com)
sjinzh (sjinzh@gmail.com), xBLACICEx (xBLACKICEx@outlook.com)

2023-02-14 12:31 UTC, sjinzh commented on codes/rust/include/print_util.rs
> + * Author: sjinzh (sjinzh@gmail.com), (xBLACKICEx@outlook.com)
sjinzh (sjinzh@gmail.com), xBLACICEx (xBLACKICEx@outlook.com)

2023-02-15 12:32 UTC, sjinzh approved these changes
@krahets It's OK.

2023-02-15 13:31 UTC, krahets approved these changes

2023-02-15 13:32 UTC, merged