✨ feat(rust/sorting) add insertion and merge sort code
krahets/hello-algo pull request #369
Opened 2023-02-15 13:36 UTC by xBLACKICEx

If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).
![image](https://user-images.githubusercontent.com/51036094/219041755-7361843a-a2da-4aff-b4ed-cf1efd1247c5.png)

2023-02-15 13:49 UTC, krahets commented
To be reviewed by @sjinzh

2023-02-17 13:59 UTC, sjinzh requested changes

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/insertion_sort.rs
> +include!("../include/include.rs");
>```
>/*
> * File: insertion_sort.rs
> * Created Time: 2023-02-13
> * Author: xBLACKICEx (xBLACKICEx@outlook.com)
> */
>
>include!("../include/include.rs");
>```

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/merge_sort.rs
> + * File: merge_sort.swift
>```
> * File: merge_sort.rs
>```

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/merge_sort.rs
> +fn merge_sort(left: usize, right: usize, nums: &mut [i32]) {
>```
>/* 归并排序 */
>fn merge_sort(left: usize, right: usize, nums: &mut [i32]) {
>```

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/quick_sort.rs
> + * File: quick_sort.cpp
>```
> * File: quick_sort.rs
>```

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/quick_sort.rs
> +/* 快速排序 */
/* 快速排序类 */

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/quick_sort.rs
> +impl QuickSortMedian {
/* 快速排序类（中位基准数优化） */

2023-02-17 13:59 UTC, sjinzh commented on codes/rust/chapter_sorting/quick_sort.rs
> +/* 快速排序（尾递归优化） */
/* 快速排序类（尾递归优化） */

2023-02-17 14:51 UTC, xBLACKICEx commented on codes/rust/chapter_sorting/quick_sort.rs
> +/* 快速排序 */
rust 里没有类所以不写“类”，参考go语言

2023-02-18 03:43 UTC, sjinzh approved these changes
@krahets  It's OK.

2023-02-18 17:00 UTC, krahets approved these changes

2023-02-18 17:00 UTC, merged