✨ feat(rust/hashing): add array_hash_map
krahets/hello-algo pull request #373
Opened 2023-02-18 23:15 UTC by xBLACKICEx

If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).
![image](https://user-images.githubusercontent.com/51036094/219903564-b39cb6ad-0130-4e06-92c8-d1225a4af2d4.png)

2023-02-21 13:42 UTC, krahets commented
To be reviewed by @sjinzh

2023-02-21 15:44 UTC, sjinzh requested changes

2023-02-21 15:44 UTC, sjinzh commented on codes/rust/chapter_hashing/array_hash_map.rs
> +    // /* 初始化哈希表 */
/* 初始化哈希表 */

2023-02-21 15:44 UTC, sjinzh commented on codes/rust/chapter_hashing/array_hash_map.rs
> +    // // 在哈希表中添加键值对 （key, value）
/*添加操作 */
// 在哈希表中添加键值对 （key, value）

2023-02-23 13:58 UTC, sjinzh approved these changes
@krahets  It's OK.

2023-02-23 15:02 UTC, krahets approved these changes

2023-02-23 15:02 UTC, merged