The Rust version of the selection sort.
krahets/hello-algo pull request #524
Opened 2023-05-30 14:35 UTC by WSL0809

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

2023-05-30 17:08 UTC, krahets commented
To be reviewed by @sjinzh

2023-05-31 14:49 UTC, WSL0809 commented
and The Rust version of the binary_search_edge

2023-06-16 17:04 UTC, krahets commented on codes/rust/chapter_searching/binary_search_edge.rs
> +fn binary_search_right_edge(nums: &[i32], target: i32) -> i32 {
same as above

2023-06-16 17:04 UTC, krahets commented on codes/rust/chapter_sorting/selection_sort.rs
> +fn selection_sort(nums: &mut [i32]) {
same

2023-06-16 17:06 UTC, krahets commented on codes/rust/chapter_sorting/selection_sort.rs
> +fn main() {
/* Driver Code */

2023-06-17 08:19 UTC, WSL0809 commented on codes/rust/chapter_searching/binary_search_edge.rs
> +fn binary_search_left_edge(nums: &[i32], target: i32) -> i32 {
I have updated the code.

2023-06-19 15:33 UTC, sjinzh requested changes
Request changes.

2023-06-19 15:33 UTC, sjinzh commented on codes/rust/chapter_sorting/selection_sort.rs
> +    for i in 0..n - 1 {
for i in 0..n-1 {

2023-06-19 15:33 UTC, sjinzh commented on codes/rust/chapter_sorting/selection_sort.rs
> +        for j in i + 1..n {
for j in i+1..n {

2023-06-19 15:33 UTC, sjinzh commented on codes/rust/chapter_searching/binary_search_edge.rs
> +    /* Driver Code */
/* Driver Code */
pub fn main() {

2023-06-20 09:57 UTC, WSL0809 commented on codes/rust/chapter_searching/binary_search_edge.rs
> +    /* Driver Code */
Code has been updated.

2023-06-25 13:00 UTC, krahets approved these changes
Thanks for the PR!

2023-06-25 13:00 UTC, merged