feat: add rust code for build_in_hash
krahets/hello-algo pull request #582
Opened 2023-07-06 03:32 UTC by WSL0809

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

2023-07-08 18:58 UTC, krahets commented on codes/rust/chapter_hashing/hash_map_chaining.rs
> +    fn put(&mut self, key: i32, val: String) {
method comment

2023-07-08 18:59 UTC, krahets commented on codes/rust/chapter_hashing/hash_map_chaining.rs
> +    // 删除操作
/* 删除操作 */

2023-07-08 19:00 UTC, krahets commented
Hi @WSL0809 , please check the code and comment to make them consistent with the reference code (Java or Python)

2023-07-10 03:13 UTC, WSL0809 commented
Thanks for the correction, I've changed the function comment @krahets

2023-07-12 10:16 UTC, krahets commented
@sjinzh Please review this PR, thx!

2023-07-12 16:06 UTC, sjinzh requested changes
@krahets 
Request changes .

2023-07-12 16:06 UTC, sjinzh commented on codes/rust/chapter_hashing/hash_map_chaining.rs
> +        // 若无该 key ,则添加新的键值对
// 若无该 key ，则将键值对添加至尾部

2023-07-12 16:06 UTC, sjinzh commented on codes/rust/chapter_hashing/hash_map_chaining.rs
> +    /* 测试代码 */
/* 初始化哈希表 */

2023-07-14 02:34 UTC, WSL0809 commented
> @krahets Request changes .

Changes made. Please re-review. Thanks!

2023-07-15 14:51 UTC, krahets commented
Hi @WSL0809 , could you please implement `hash_map_open_addressing.rust` and push to this PR?

2023-07-15 15:14 UTC, WSL0809 commented
> Hi @WSL0809 , could you please implement `hash_map_open_addressing.rust` and push to this PR? Because we wonder all the codes in hash collision implemented in one PR.

sure！

2023-07-18 02:24 UTC, closed without merging